plugins: {}
filters:
  comments: true
  allowlist:
    allowlistConfigPaths:
      - .textlint/allowlist.yaml
rules:
  preset-japanese:
    sentence-length:
      max: 120
    max-kanji-continuous-len:
      max: 8
      allow: []
  preset-ja-spacing:
    ja-space-between-half-and-full-width:
      space:
        - alphabets
        - numbers
  "ja-hiraku": true
  ja-no-orthographic-variants: true
  "@textlint-ja/textlint-rule-no-synonyms": true
  no-mixed-zenkaku-and-hankaku-alphabet: true
  "@proofdict/proofdict":
    dictURL: "https://atsushifx.github.io/proof-dictionary/"
  prh:
    rulePaths:
      - ./.textlint/dict/prh.yml
